### ISSUE TITLE
How would you go about disabling random number comparisons on the board

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/sudoku-applitools#3]
Every time a new game starts the board is new - how do we compare the entire board but ignore the number

![Screen Shot 2020-09-19 at 11 11 54 AM](https://user-images.githubusercontent.com/2212006/93670375-ef816980-fa68-11ea-84ff-66368bd4ca9e.png)

- is there something built into Applitools?
- can we pass CSS to ignore during the snapshot?

**Comment by giltayar** [comment]
We have something called "Layout mode" that compares the layout and not the actual data. It can even do it when the number of rows is different and lots of other stuff. In this case, I wouldn't use layout mode, but rather a layout region, which compares a specific region by layout, and not the whole page.

**Comment by giltayar** [comment]
Fixed in latest push
